### ISSUE TITLE
Extra songs

### ISSUE THREAD

**Issue by brnwlshubh** [sweakpl/smart-alarm-android#1]
Please add extra songs(like disturbing or loud one) which makes a user unavoidable and makes him to get up with alarm.

Alternative example:-https://play.google.com/store/apps/details?id=droom.sleepIfUCan it contain same feature which I want.

**Comment by sweakpl** [comment]
Thanks for Your feedback! At first I didn't want to make the app too intrusive, like the one in the link, but the mechanisms used in the other alarm clock look interesting and I see why they might be desirable,

I will work on new features and see what can be done as soon as possible (as of today, as a student, exams and deadlines at univeristy take majority of my time, but that will end soon).

Once again, thanks for Your contribution!

**Comment by brnwlshubh** [comment]
I only want inclusion of songs(or like this sound) it have(like loud or disturbing sound)from the mentioned app.
If possible try to include in next upcoming version/update.

**Comment by sweakpl** [comment]
Allright! I will take it into account in the future development.

**Comment by sweakpl** [comment]
I'm closing the issue because it has been resolved - new alarm tones have been added in the latest release (1.1).
