### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by IzzySoft** [sweakpl/smart-alarm-android#2]
I see proper attribution for assets used, which is great – thanks for that! Could you also include what license the app itself falls under? Thanks in advance!

**Comment by sweakpl** [comment]
Sure!

**Comment by IzzySoft** [comment]
Great choice, thanks a lot! That makes it FOSS then. I've thus added your app to my repo now, it should [show up here](https://apt.izzysoft.de/fdroid/index/apk/com.sweak.smartalarm) with the next sync tomorrow around 7 pm UTC. Be welcome using [these badges](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) if you want to link there – and Android users can now simply use any [F-Droid client](https://android.izzysoft.de/applists/category/named/apps_markets#group_1181) to install it and keep it updated.

Should you want to head over to the [F-Droid.org](https://f-droid.org/) repo with your app, you can simply open a [Request For Packaging](https://gitlab.com/fdroid/rfp/issues). From the results of my scanner, I see no show-stopper for that (F-Droid has a bit stricter rules than my repo – but for that also is more trusted).

**Comment by sweakpl** [comment]
Oh wow, nice stuff @IzzySoft ! Is the repo synchronized in some way with my repo here on GitHub? Say, I create a newer release - will it sync, or will I have to update manually?

**Comment by IzzySoft** [comment]
> Oh wow, nice stuff

Glad you like it! :smiley:

> Is the repo synchronized in some way with my repo here on GitHub? Say, I create a newer release - will it sync, or will I have to update manually?

As long as you keep the naming conventions you currently use, my update checker should find the new release within 24h and automatically pull the APK attached to it – so no manual steps needed usually. Update cycle usually runs between 7 pm and 8 pm Berlin time (i.e. currently 6/7 pm UTC).
